name: Build ARM64 Container
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ipxbox:latest . 
          
      - name: Build and push container
        run: |
          docker push ghcr.io/${{ github.repository }}/ipxbox:latest
          #platforms: linux/arm64
          
